# Custom vars
name: ¿Qué hacer en Tierra del Fuego?
description: > # this means to ignore newlines until "baseurl:"
  Listado de actividades y eventos que se hacen en Tierra del fuego.
baseurl: "" # the subpath of your site, e.g. /blog/ # if it's not in root of domain # GitHub sets this to the domain name (example.github.io/project) or custom CNAME
url: &site_url "http://tdf.aquinzi.com" # the base hostname & protocol for your site

github:
    repository_nwo: eikiu/tdf-actividades
    url: *site_url #should be using above config, but keep it until we clean everything
    repository_url: https://github.com/eikiu/tdf-actividades
    # below not in usage
    repository_name: tdf-actividades
    owner_name: eikiu 
    issues_url: https://github.com/eikiu/tdf-actividades/issues
    wiki_url:   https://github.com/eikiu/tdf-actividades/wiki
    clone_url:  https://github.com/eikiu/tdf-actividades.git 

    # custom github data
    branch: gh-pages

google_analytics: UA-65450271-1

social:
  twitter: 
    url: https://twitter.com/quehacerentdf/
    handle: "@quehacerentdf"
  facebook:
    url: http://facebook.com/quehacerentdf/
    handle: Qué hacer en TdF
  form_colaboracion: https://docs.google.com/forms/d/1OQ8bvzPfGqR5Q6dpBTUGd1y-7FIXtd9Op5eOm2o-TYk/viewform #put it here for now
  form_contacto: https://docs.google.com/forms/d/1r_YkIk9w58ZofjwwPvzHd4SKZBhxkHj4T_O7OGjrOo8/viewform

email:
  contacto: tdf.actividades+contacto@gmail.com

feed:
  riogrande: "/feed-rio-grande.xml"
  ushuaia: "/feed-ushuaia.xml"
  tolhuin: "/feed-tolhuin.xml"


# some data that we don't know where to put it (yet), and not in usage
adultos_mayores:
  edad: más de 60 años
  newcom: voley modificado o adaptado


# Jekyll Configuration options. 
# ------------------------------
#   commented options are default values

# Where things are
#source:       . #  GitHub Pages = top-level directory/root of repository
#destination:  ./_site #must keep this for GitHub Pages
#plugins_dir:  ./_plugins
#layouts_dir:  ./_layouts
#data_dir:     ./_data
#includes_dir: ./_includes
#collections:  null

# Handling Reading
safe: true # for GitHub Pages, can't be overwritten
include: 
   - _pages
exclude: 
   - LICENSE
   - README.md
   - CNAME
   - _admin-scripts
   - cacert.pem 
   - documentacion.html
   - Gemfile
   - Gemfile.lock
   - iniciar.bat 
#keep_files:   [".git", ".svn"] # Useful for files not generated by jekyll (e.g. files generated by a build tool). Paths relative to destination.
#encoding:     "utf-8"
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Filtering Content
#show_drafts: null
#limit_posts: 0 #number of posts to parse and publish.
future: true #Publish posts with a future date 
#unpublished: false

# Plugins
#whitelist: []
# below are all Allowed in GitHub Pages
gems:
   - jekyll-sitemap 
#   - jemoji # emoji
#   - jekyll-mentions # support for @mentions (github users)
#   - jekyll-feed 
   - jekyll-redirect-from # in posts/pages use: redirect_from: "/foo"

# jekyll-redirect-from: 
#     allow an author to specify multiple URLs for a page, such that the alternative URLs redirect to the new Jekyll URL. 
#     To use it, simply add the array to the YAML front-matter of your page or post:
#        title: My amazing post
#        redirect_from:
#          - /post/123456789/
#          - /post/123456789/my-amazing-post/
#     This automatically creates the html files in those directories, containing an HTTP-REFRESH meta tag which redirect to your URL.
#     You can also redirect to a different URL with: redirect_to

# Conversion
#markdown:    kramdown
highlighter: rouge 
#lsi:         false # related posts; can't overwrite in GitHub Pages 
#excerpt_separator: "\n\n"

# Serving
#detach:  false # Detach server from terminal . Also in cmd: -B, --detach
#port:    4000
#host:    127.0.0.1
#baseurl: "" # does not include hostname

# Outputting
# permalinks pretty = /:categories/:year/:month/:day/:title/
permalink: /:categories/agenda/:year/:month/:title/ # one category (the city)
#paginate: 5 # it's not by default. If not enabled = no pagination
#paginate_path: /page:num
timezone: America/Argentina/Ushuaia
#relative_permalinks: false # Default 2.0. Option will be removed in Jekyll v3.

#quiet: false

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      show_source: true
      show_history: true
  -
    scope:
      path: "" 
      type: posts
    values:
      layout: event
      breadcrumb_limit: 3
      show_source: true
      show_history: false
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: pages
    values:
      #category: "agenda"
      layout: page
  -
    scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  -
    scope:
      path: "tags" 
      type: "pages"
    values:
      layout: tag
      show_source: false
      show_history: false
  - 
    scope:
      path: ""
      type: entidades-riogrande
    values:
      layout: entity
      breadcrumb_limit: 3
      city: rio-grande

collections:
  entidades-riogrande:
    output: true 
    permalink: /rio-grande/entidades/:path/

# Markdown Processors (include only kramdown)

#kramdown:
#  auto_ids:       true
#  footnote_nr:    1
#  entity_output:  as_char
#  toc_levels:     1..6
#  smart_quotes:   lsquo,rsquo,ldquo,rdquo
#  enable_coderay: false
#
#  coderay:
#    coderay_wrap:              div
#    coderay_line_numbers:      inline
#    coderay_line_number_start: 1
#    coderay_tab_width:         4
#    coderay_bold_every:        10
#    coderay_css:               style
#  input: GFM #not default # turn on recognition of Github Flavored Markdown 

# Github Flavored Markdown (https://help.github.com/articles/github-flavored-markdown/)
#    - ignores underscores when in-between words
#    - autolinks URLs
#    - strikethrough ( ~~deleteed~~ )
#    - fenced code blocks with ```
#    - syntax highlighting: ```lang
#    - tables